#! /bin/bash
##写一个脚本实现如下功能：  输入一个数字，然后运行对应的一个命令。1---date 2--ls 3--who 4--pwd

#! /bin/bash
echo "*cmd meau**  1---date 2--ls 3--who 4--pwd"
read -p "please input a number 1-4: " n
case $n in
    1)
        date
        ;;
    2)
        ls
        ;;
    3)
        who
        ;;
    4)
        pwd
        ;;
    *)
        echo "Please input a number: 1-4"
        ;;
esac
